const movies = [
    {_id:1,"Title": "The Land Girls", "US Gross": 146083, "Worldwide Gross": 146083, "US DVD Sales": null, "Production Budget": 8000000, "Release Date": "Jun 12 1998", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Gramercy", "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.1, "IMDB Votes": 1071},
    {_id:2,"Title": "First Love, Last Rites", "US Gross": 10876, "Worldwide Gross": 10876, "US DVD Sales": null, "Production Budget": 300000, "Release Date": "Aug 07 1998", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Strand", "Source": null, "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.9, "IMDB Votes": 207},
    {_id:3,"Title": "I Married a Strange Person", "US Gross": 203134, "Worldwide Gross": 203134, "US DVD Sales": null, "Production Budget": 250000, "Release Date": "Aug 28 1998", "MPAA Rating": null, "Running Time min": null, "Distributor": "Lionsgate", "Source": null, "Major Genre": "Comedy", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.8, "IMDB Votes": 865},
    {_id:4,"Title": "Let's Talk About Sex", "US Gross": 373615, "Worldwide Gross": 373615, "US DVD Sales": null, "Production Budget": 300000, "Release Date": "Sep 11 1998", "MPAA Rating": null, "Running Time min": null, "Distributor": "Fine Line", "Source": null, "Major Genre": "Comedy", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 13, "IMDB Rating": null, "IMDB Votes": null},
    {_id:5,"Title": "Slam", "US Gross": 1009819, "Worldwide Gross": 1087521, "US DVD Sales": null, "Production Budget": 1000000, "Release Date": "Oct 09 1998", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Trimark", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": 62, "IMDB Rating": 3.4, "IMDB Votes": 165},
    {_id:6,"Title": "Mississippi Mermaid", "US Gross": 24551, "Worldwide Gross": 2624551, "US DVD Sales": null, "Production Budget": 1600000, "Release Date": "Jan 15 1999", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {_id:7,"Title": "Following", "US Gross": 44705, "Worldwide Gross": 44705, "US DVD Sales": null, "Production Budget": 6000, "Release Date": "Apr 04 1999", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Zeitgeist", "Source": null, "Major Genre": null, "Creative Type": null, "Director": "Christopher Nolan", "Rotten Tomatoes Rating": null, "IMDB Rating": 7.7, "IMDB Votes": 15133},
    {_id:8,"Title": "Foolish", "US Gross": 6026908, "Worldwide Gross": 6026908, "US DVD Sales": null, "Production Budget": 1600000, "Release Date": "Apr 09 1999", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Artisan", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 3.8, "IMDB Votes": 353},
    {_id:9,"Title": "Pirates", "US Gross": 1641825, "Worldwide Gross": 6341825, "US DVD Sales": null, "Production Budget": 40000000, "Release Date": "Jul 01 1986", "MPAA Rating": "R", "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": "Roman Polanski", "Rotten Tomatoes Rating": 25, "IMDB Rating": 5.8, "IMDB Votes": 3275},
    {_id:10,"Title": "Duel in the Sun", "US Gross": 20400000, "Worldwide Gross": 20400000, "US DVD Sales": null, "Production Budget": 6000000, "Release Date": "Dec 31 2046", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 86, "IMDB Rating": 7, "IMDB Votes": 2906},
    {_id:11,"Title": "Blazing Saddles", "US Gross": 119500000, "Worldwide Gross": 119500000, "US DVD Sales": null, "Production Budget": 2600000, "Release Date": "Jan 01 1974", "MPAA Rating": null, "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": null, "Director": "Mel Brooks", "Rotten Tomatoes Rating": 89, "IMDB Rating": 7.8, "IMDB Votes": 45771},
    {_id:12,"Title": "The Basket", "US Gross": 609042, "Worldwide Gross": 609042, "US DVD Sales": null, "Production Budget": 1300000, "Release Date": "May 05 2000", "MPAA Rating": "PG", "Running Time min": null, "Distributor": "MGM", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.3, "IMDB Votes": 343},
    {_id:13,"Title": "Bathing Beauty", "US Gross": 3500000, "Worldwide Gross": 3500000, "US DVD Sales": null, "Production Budget": 2361000, "Release Date": "Dec 31 1943", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Original Screenplay", "Major Genre": "Musical", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.2, "IMDB Votes": 487},
    {_id:14,"Title": "Bill & Ted's Excellent Adventure", "US Gross": 39916091, "Worldwide Gross": 39916091, "US DVD Sales": null, "Production Budget": 10000000, "Release Date": "Feb 17 1989", "MPAA Rating": null, "Running Time min": null, "Distributor": "Orion Pictures", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Science Fiction", "Director": "Stephen Herek", "Rotten Tomatoes Rating": 81, "IMDB Rating": 6.7, "IMDB Votes": 30341},
    {_id:15,"Title": "A Bridge Too Far", "US Gross": 50800000, "Worldwide Gross": 50800000, "US DVD Sales": null, "Production Budget": 26000000, "Release Date": "Jun 15 1977", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Action", "Creative Type": null, "Director": "Sir Richard Attenborough", "Rotten Tomatoes Rating": 67, "IMDB Rating": 7.3, "IMDB Votes": 16882},
    {_id:16,"Title": "Beetle Juice", "US Gross": 73326666, "Worldwide Gross": 73326666, "US DVD Sales": null, "Production Budget": 15000000, "Release Date": "Mar 30 1988", "MPAA Rating": null, "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Fantasy", "Director": "Tim Burton", "Rotten Tomatoes Rating": null, "IMDB Rating": 7.3, "IMDB Votes": 61197},
    {_id:17,"Title": "Batman Returns", "US Gross": 162831698, "Worldwide Gross": 266822354, "US DVD Sales": null, "Production Budget": 80000000, "Release Date": "Jun 18 1992", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Super Hero", "Director": "Tim Burton", "Rotten Tomatoes Rating": 78, "IMDB Rating": 6.9, "IMDB Votes": 78673},
    {_id:18,"Title": "Batman Forever", "US Gross": 184031112, "Worldwide Gross": 336529144, "US DVD Sales": null, "Production Budget": 100000000, "Release Date": "Jun 16 1995", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Action", "Creative Type": "Super Hero", "Director": "Joel Schumacher", "Rotten Tomatoes Rating": 43, "IMDB Rating": 5.4, "IMDB Votes": 76218},
    {_id:19,"Title": "Batman - The Movie", "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 1377800, "Release Date": "Aug 21 2001", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": null, "IMDB Votes": null},
    {_id:20,"Title": "Batman", "US Gross": 251188924, "Worldwide Gross": 411348924, "US DVD Sales": null, "Production Budget": 35000000, "Release Date": "Jun 23 1989", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Based on Comic/Graphic Novel", "Major Genre": "Action", "Creative Type": "Super Hero", "Director": "Tim Burton", "Rotten Tomatoes Rating": 71, "IMDB Rating": 7.6, "IMDB Votes": 111464},
    {_id:21,"Title": "Buffy the Vampire Slayer", "US Gross": 14231669, "Worldwide Gross": 14231669, "US DVD Sales": null, "Production Budget": 7000000, "Release Date": "Jul 31 1992", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Original Screenplay", "Major Genre": "Horror", "Creative Type": "Fantasy", "Director": null, "Rotten Tomatoes Rating": 32, "IMDB Rating": 5.3, "IMDB Votes": 16056},
    {_id:22,"Title": "Bienvenue chez les Ch'tis", "US Gross": 1470856, "Worldwide Gross": 243470856, "US DVD Sales": null, "Production Budget": 16000000, "Release Date": "Jul 25 2008", "MPAA Rating": "Not Rated", "Running Time min": 109, "Distributor": "Link Productions Ltd.", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 7, "IMDB Votes": 7129},
    {_id:23,"Title": "Beyond the Valley of the Dolls", "US Gross": 9000000, "Worldwide Gross": 9000000, "US DVD Sales": null, "Production Budget": 1000000, "Release Date": "Jan 01 1970", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 68, "IMDB Rating": 5.7, "IMDB Votes": 4626},
    {_id:24,"Title": "Broken Vessels", "US Gross": 15030, "Worldwide Gross": 85343, "US DVD Sales": null, "Production Budget": 600000, "Release Date": "Jul 02 1999", "MPAA Rating": "R", "Running Time min": null, "Distributor": null, "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6.4, "IMDB Votes": 399},
    {_id:25,"Title": "The Boys from Brazil", "US Gross": 19000000, "Worldwide Gross": 19000000, "US DVD Sales": null, "Production Budget": 12000000, "Release Date": "Dec 31 1977", "MPAA Rating": null, "Running Time min": null, "Distributor": "20th Century Fox", "Source": "Based on Book/Short Story", "Major Genre": "Thriller/Suspense", "Creative Type": null, "Director": "Franklin J. Schaffner", "Rotten Tomatoes Rating": 65, "IMDB Rating": 7, "IMDB Votes": 8741},
    {_id:26,"Title": "The Business of Fancy Dancing", "US Gross": 174682, "Worldwide Gross": 174682, "US DVD Sales": null, "Production Budget": 200000, "Release Date": "May 10 2002", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Outrider Pictures", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 7, "IMDB Votes": 355},
    {_id:27,"Title": "Caddyshack", "US Gross": 39846344, "Worldwide Gross": 39846344, "US DVD Sales": null, "Production Budget": 6000000, "Release Date": "Jul 25 1980", "MPAA Rating": null, "Running Time min": null, "Distributor": "Warner Bros.", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "Harold Ramis", "Rotten Tomatoes Rating": 75, "IMDB Rating": 7.3, "IMDB Votes": 35436},
    {_id:28,"Title": "Cape Fear", "US Gross": 79091969, "Worldwide Gross": 182291969, "US DVD Sales": null, "Production Budget": 35000000, "Release Date": "Nov 15 1991", "MPAA Rating": "R", "Running Time min": null, "Distributor": "Universal", "Source": "Remake", "Major Genre": "Thriller/Suspense", "Creative Type": "Contemporary Fiction", "Director": "Martin Scorsese", "Rotten Tomatoes Rating": 76, "IMDB Rating": 7.3, "IMDB Votes": 47196},
    {_id:29,"Title": "Clear and Present Danger", "US Gross": 122012656, "Worldwide Gross": 207500000, "US DVD Sales": null, "Production Budget": 62000000, "Release Date": "Aug 03 1994", "MPAA Rating": "PG-13", "Running Time min": null, "Distributor": "Paramount Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Action", "Creative Type": "Contemporary Fiction", "Director": "Phillip Noyce", "Rotten Tomatoes Rating": 78, "IMDB Rating": 6.8, "IMDB Votes": 29612},
    {_id:30,"Title": "Carrie", "US Gross": 25878153, "Worldwide Gross": 25878153, "US DVD Sales": null, "Production Budget": 1800000, "Release Date": "Nov 16 1976", "MPAA Rating": null, "Running Time min": null, "Distributor": "MGM", "Source": "Based on Book/Short Story", "Major Genre": "Horror", "Creative Type": "Contemporary Fiction", "Director": "Brian De Palma", "Rotten Tomatoes Rating": 90, "IMDB Rating": 7.4, "IMDB Votes": 38767},
    {_id:31,"Title": "Casino Royale", "US Gross": 22744718, "Worldwide Gross": 41744718, "US DVD Sales": null, "Production Budget": 12000000, "Release Date": "Apr 28 1967", "MPAA Rating": null, "Running Time min": null, "Distributor": "Sony Pictures", "Source": "Based on Book/Short Story", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": "John Huston", "Rotten Tomatoes Rating": 30, "IMDB Rating": 8, "IMDB Votes": 172936},
    {_id:32,"Title": "Camping Sauvage", "US Gross": 3479302, "Worldwide Gross": 3479302, "US DVD Sales": null, "Production Budget": 4600000, "Release Date": "Jul 16 2004", "MPAA Rating": "Not Rated", "Running Time min": null, "Distributor": "Alliance", "Source": "Original Screenplay", "Major Genre": "Comedy", "Creative Type": "Contemporary Fiction", "Director": null, "Rotten Tomatoes Rating": null, "IMDB Rating": 6, "IMDB Votes": 378},
    {_id:33,"Title": "The Cotton Club", "US Gross": 25928721, "Worldwide Gross": 25928721, "US DVD Sales": null, "Production Budget": 48000000, "Release Date": "Dec 14 1984", "MPAA Rating": null, "Running Time min": null, "Distributor": "Orion Pictures", "Source": "Original Screenplay", "Major Genre": "Drama", "Creative Type": "Historical Fiction", "Director": "Francis Ford Coppola", "Rotten Tomatoes Rating": 74, "IMDB Rating": 6.3, "IMDB Votes": 6940},
    {_id:34,"Title": "Crop Circles: Quest for Truth", "US Gross": 0, "Worldwide Gross": 0, "US DVD Sales": null, "Production Budget": 600000, "Release Date": "Aug 23 2002", "MPAA Rating": null, "Running Time min": null, "Distributor": null, "Source": null, "Major Genre": null, "Creative Type": null, "Director": null, "Rotten Tomatoes Rating": 60, "IMDB Rating": 7.1, "IMDB Votes": 153}
]

export function getMovies(){
    return movies;
}

export function getMovie(id){
    return movies.find(m=>m.id===id);
}